### ISSUE TITLE
Your Readme file is malformed

### ISSUE THREAD

**Issue by dabockster** [HolyArchangel/dbbackup#1]
You need to separate new lines by a blank line between each block of text.

`Author: Sean Themar
Introduction:
dbbackup is a script that creates .csv backup files of a MS SQL Server Database's tables.
The script creates a folder with the current date and creates a .csv for each table in the 
database.  If the folder already exists, the files are overwritten.
`

This shows up as one line because it is not separated.

It should be this:

```
Author: Sean Themar

Introduction:

dbbackup is a script that creates .csv backup files of a MS SQL Server Database's tables.
The script creates a folder with the current date and creates a .csv for each table in the 
database.  If the folder already exists, the files are overwritten.
```

More GitHub flavored markdown can be found here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by AstolfoCoding** [comment]
Oops, I didn't realize I didn't separate Author and Intro.  Thanks for catching that!
